# Конфигурационный файл приложения.
# Тут будут описаны параметры spring-boot приложения и другие конфиги.
# Можно использовать один файл, можно несколько.
# Поскольку наши сервисы будут микро, то будем весь конфиг хранить в одном файле соответствующем сервису.
---
server:
  port: ${PORT:8085} # Порт приложения
---
spring:
  data:
    mongodb: # Параметры подключения к БД
      uri: 'mongodb+srv://${MONGODB_SERVER_USERNAME:admin}:${MONGODB_SERVER_PASSWORD}@${MONGODB_CLUSTER_URI:localHost:27017}/${MONGODB_DB:mapDb}'
      authentication-database: ${MONGODB_AUTH_DB:admin}
      gridfs:
        database: ${MONGODB_DB:mapDb}
      uuid-representation: java_legacy
---
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    mongo:
      enabled: true
---
init:
  db:
    enable: ${INIT_DB_ENABLE:false}
    images:
      filepath: ${IMAGES_FILEPATH}